# Generated by Django 4.2 on 2023-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_descriptions_user_instagram_user_locate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
