# Generated by Django 4.2 on 2023-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='locate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='maps',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Адрес по карте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер'),
        ),
    ]
