# Generated by Django 4.2 on 2023-04-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_setting_maps_setting_address_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.CharField(max_length=255, verbose_name='Количество учителей')),
                ('students', models.TextField(verbose_name='Количество студентов')),
                ('company', models.TextField(verbose_name='Количество комании в которых работают')),
                ('alumni', models.TextField(verbose_name='Количество выпускников')),
            ],
            options={
                'verbose_name': 'Мы в числах',
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
