# Generated by Django 4.2 on 2023-04-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
