# Generated by Django 4.2 on 2023-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
    ]
