# Generated by Django 4.2 on 2023-05-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
