# Generated by Django 4.2 on 2023-06-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_setting_telegram'),
        ('settings', '0012_rename_contacts_contact'),
    ]

    operations = [
    ]
